### ISSUE TITLE
discussion: onboarding members

### ISSUE THREAD

**Issue by twilson63** [twilson63/swag.arweave.dev#5]
The goal should be as accessible as possible without sharing any secrets with the core app.

So there will be three entry points: (may change depending on swag)

```
/ - Leaderboard
/?tx={PLAYER_TX} - render with
/?id={UNIQUE_ID} - scanned from QR Code
```

---
The current thinking concept is if they do an action that requires a sign transaction is to walk them through a wallet wizard workflow.
Check for arweaveWallet if there then try to connect with it
If not prompt them to use Arweave.app on mobile or create a wallet
If create a wallet, show there keywords and allow them to save the keyFile to disk - if mobile store keyFile securely in localStorage, so they can always use the app on that device

The idea is to keep it simple for users to use, but we also should consider sybil attacks so I recommend that the user can only generate a keyFile one time.

And when they use a keyFile it basically injects an object into memory that emulates the features of the arweaveWallet, so the application does not have to do any kind of logic around am I a keyFile or a Wallet.

---

Here is a proposal for webmobile wallet

https://pbrfiiwghky5a33t3qudwoq6cwtu5nz2jesus4yjbqw3q5tmxfoq.arweave.net/eGJUIsY6sdBvc9woOzoeFadOtzpJJUlzCQwtuHZsuV0

**Comment by VinceJuliano** [comment]
Got it cool. So are we planning to develop the web mobile wallet as the includable library alongside Swag or are we planning to do a sort of test iteration on the concept within the Swag repo?

**Comment by twilson63** [comment]
Maybe a test iteration for starters

**Comment by twilson63** [comment]
![StampGameFlow](https://user-images.githubusercontent.com/21292/219952630-013acc42-2817-4acc-88c9-fb4ef424cf69.png)
