### ISSUE TITLE
feat: game state contract

### ISSUE THREAD

**Issue by twilson63** [twilson63/swag.arweave.dev#55]
In order to prevent cybil attacks we may consider to manage the player list in a smart contract, this would be a simple contract that just keeps a list of players.

```js
{
  players: {
    [qr code]: [PLAYER_TX_ID] // value would be their Atomic Token Profile TX ID
  },
  name: 'EthDenver'
}
```

methods 

- register = connects a qr code with a TX_ID
- slash = admin only function removing a TX_ID from a qr code

```js
@callback Register
@param {string} qrCode
@param {string} txId
```

```js
@callback Slash
@param {string} qrCode
```

**Comment by DanMacDonald** [comment]
As each update to a profile creates a new txid, it might be worth attaching this to the owners address as opposed to the specific TXID of a specific profile  update.

**Comment by twilson63** [comment]
Maybe both, having the TX_ID will make querying faster

```js
{
  players: {
    [qr]: { address: 'XXXX', token: 'XXXX' }
  }
}
```

**Comment by twilson63** [comment]
> As each update to a profile creates a new txid, it might be worth attaching this to the owners address as opposed to the specific TXID of a specific profile update.

Also, just for clarity they would not be able to update their arProfile using other methods, the point is to use Atomic Token so that they can also get stamp rewards the Atomic Token is just sharing the same dataset as the arprofile and will work as their profile for the game.

But if they update it somewhere else it will not update in the game

**Comment by twilson63** [comment]
Unless we detatch the two, which is fine too, but the TX_ID in the contract is not the arProfile TX it is the Atomic Token TX. My original thoughts were keeping them one in in the same, but now maybe they should be split out, of course this is more token signing dialogs

**Comment by DanMacDonald** [comment]
It would be nice to have the permaweb experience of arProfile showing up in other apps.  (like if arweave.app supported it!)

**Comment by twilson63** [comment]
👋 

I am working on the game contract and currently think this flow could work:

-> User Receives Hoodie, they scan and register, which makes them a player in the game, pending approval, the person at the booth is a player that is flagged as an admin, if they are an admin then they can approve players in the game.

This means we would have an admin screen that allowed admins to approve players once they are registered. this should prevent unwanted users from playing the game.

Also these admins will be able to slash players from the game, in the admin interface.
