### ISSUE TITLE
feat(UX): Avatar Crop Image Resize Component

### ISSUE THREAD

**Issue by twilson63** [twilson63/swag.arweave.dev#67]
When the user uploads a picture for their avatar we need to try to get the image below 100kb

Ideally using a crop and resize component.

https://imagekit.io/blog/how-to-resize-image-in-javascript/

https://img.ly/blog/how-to-compress-an-image-before-uploading-it-in-javascript/

☝️ This may be helpful, also their are some components on the svelte repl that shows how to crop and resize a photo in a component.

**Comment by twilson63** [comment]
https://gist.github.com/PBillingsby/6155538a54e6911cdff3ad98e18aae7d

**Comment by PBillingsby** [comment]
closing with #94
